### ISSUE TITLE
Example code errors

### ISSUE THREAD

**Issue by bon3s** [thechriswalker/protoc-gen-twirp_js#4]
Hello,

I've tried running this example code with every possible solution I could find, but nothing seems to work. 
When running the client , the error is 2018/12/04 11:05:41 twirp error internal: failed to do request: Post localhost:8080/twirp/twitch.twirp.example.Haberdasher/MakeHat: unsupported protocol scheme "localhost".

When running the server the error is:
.\main.go:29:38: undefined: LoggingStatter

When running the compiler manually, using

protoc --js_out=import_style=commonjs,binary:. --twirp_js_out=. --proto_path $path/to/protofile $proto_file_name.proto

it says the file cannot be found, even though the proto file is present.
I'm running it on win10, a terminal with admin rights.  Could you please check what could be the issue ? Thank you.

**Comment by thechriswalker** [comment]
I fixed the client error.

The server error is present if you `go run main.go` as the other file is ignored. `go build` instead.

The compiler error, well I hope you replaced `$path/to/protofile` and `proto_file_name.proto` with the correct values for your environment. The first should just be the path and the second the filename.
